language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"

env:

jobs:
  include:
    - stage: core
      python: 2.7
      env: TOXENV=py27
    - stage: core
      python: 3.3
      env: TOXENV=py33
    - stage: core
      python: 3.4
      env: TOXENV=py34
    - stage: core
      python: 3.5
      env: TOXENV=py35
    - stage: core
      python: 3.5
      env: TOXENV=py35
    - stage: core
      python: pypy
      env: TOXENV=pypy
    - stage: core
      python: 3.5
      env: TOXENV=flake8


    - stage: contrib django
      python: 2.7
      env: TOXENV=py27-django-16
    - stage: contrib django
      python: 2.7
      env: TOXENV=py27-django-17
    - stage: contrib django
      python: 2.7
      env: TOXENV=py27-django-18
    - stage: contrib django
      python: 2.7
      env: TOXENV=py27-django-19
    - stage: contrib django
      python: 2.7
      env: TOXENV=py27-django-110

    - stage: contrib
      python: 3.3
      env: TOXENV=py33-django-17
    - stage: contrib
      python: 3.3
      env: TOXENV=py33-django-18

    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-17
    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-18
    - stage: contrib
      python: 3.4
      env: py34-django-19
    - stage: contrib
      python: 3.4
      env: py34-django-110

    - stage: contrib
      python: 3.5
      env: py35-django-18
    - stage: contrib
      python: 3.5
      env: py35-django-19
    - stage: contrib
      python: 3.5
      env: py35-django-110

    - stage: contrib
      python: 2.7
      env: TOXENV=py27-flask-10
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-flask-11
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-10
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-11
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-12

    - stage: contrib
      python: 2.7
      env: TOXENV=py27-celery-3
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-celery-4


script: tox
install:
  - pip install tox wheel codecov "coverage<4"
before_script:
  - pip freeze
after_success:
  - codecov -e DJANGO


