language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO="1.7"
  - DJANGO="1.8"
  - DJANGO="1.9"
  - CELERY="3"
  - CELERY="4"

install:
  - pip install tox tox-travis wheel codecov "coverage<4"
before_script:
  - pip freeze
script:
  - tox
after_success:
  - codecov -e DJANGO


