language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"

env:

  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
  - TOXENV=py34-django-110
  - TOXENV=py35-django-18
  - TOXENV=py35-django-19
  - TOXENV=py35-django-110
  - TOXENV=py27-django-18
  - TOXENV=py33-django-18
  - TOXENV=py34-django-18
  - TOXENV=py35-django-18
  - TOXENV=py27-django-17
  - TOXENV=py33-django-17
  - TOXENV=py34-django-17
  - TOXENV=py27-django-16
  - TOXENV=py27-flask-10
  - TOXENV=py27-flask-11
  - TOXENV=py35-flask-10
  - TOXENV=py35-flask-11
  - TOXENV=py35-flask-10
  - TOXENV=py35-flask-11
  - TOXENV=py27-celery-3
  - TOXENV=py27-celery-4
jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py27
    - stage: test
      python: 3.3
      env: TOXENV=py33
    - stage: test
      python: 3.4
      env: TOXENV=py34
    - stage: test
      python: 3.5
      env: TOXENV=py35
    - stage: test
      python: 3.5
      env: TOXENV=py35
    - stage: test
      python: pypy
      env: TOXENV=pypy
    - stage: test
      python: 3.5
      env: TOXENV=flake8

    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-18
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-19
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-110


script: tox
install:
  - pip install tox wheel codecov "coverage<4"
before_script:
  - pip freeze
after_success:
  - codecov -e DJANGO


