language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.7"
  - "3.5"

script: tox
install:
  - pip install tox tox-env wheel codecov "coverage<4"
before_script:
  - pip freeze
after_success:
  - codecov -e DJANGO


